# Generated by Django 2.2.6 on 2019-10-20 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import journal.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEntry',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pair', models.CharField(max_length=7)),
                ('option', models.CharField(choices=[('b', 'Buy'), ('s', 'Sell')], default='b', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('date', models.DateField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option', models.CharField(blank=True, choices=[('forex', 'forex'), ('binary', 'binary')], max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=journal.models.ContentBase.user_directory_path)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('text', models.TextField()),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reason', to='journal.BaseEntry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=journal.models.ContentBase.user_directory_path)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('text', models.TextField()),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='journal.BaseEntry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForexEntry',
            fields=[
                ('baseentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.BaseEntry')),
                ('timeStart', models.DateTimeField()),
                ('timeEnded', models.DateTimeField()),
                ('rMultiple', models.IntegerField()),
                ('SL', models.FloatField()),
                ('price', models.FloatField()),
                ('TP', models.FloatField()),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forex', to='journal.TimeStamp')),
            ],
            bases=('journal.baseentry',),
        ),
        migrations.CreateModel(
            name='BinaryEntry',
            fields=[
                ('baseentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.BaseEntry')),
                ('payout', models.IntegerField()),
                ('result', models.CharField(choices=[('w', 'Win'), ('l', 'Lose')], max_length=1)),
                ('time', models.TimeField()),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binary', to='journal.TimeStamp')),
            ],
            bases=('journal.baseentry',),
        ),
    ]
