# Generated by Django 2.2.6 on 2019-10-12 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('date', models.DateField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option', models.CharField(blank=True, choices=[('forex', 'forex'), ('binary', 'binary')], max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForexEntry',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pair', models.CharField(max_length=7)),
                ('option', models.CharField(choices=[('b', 'Buy'), ('s', 'Sell')], default='b', max_length=1)),
                ('reasons', models.TextField()),
                ('lessons', models.TextField()),
                ('timeStart', models.DateTimeField()),
                ('timeEnded', models.DateTimeField()),
                ('rMultiple', models.IntegerField()),
                ('SL', models.FloatField()),
                ('price', models.FloatField()),
                ('TP', models.FloatField()),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forex', to='journal.TimeStamp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinaryEntry',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pair', models.CharField(max_length=7)),
                ('option', models.CharField(choices=[('b', 'Buy'), ('s', 'Sell')], default='b', max_length=1)),
                ('reasons', models.TextField()),
                ('lessons', models.TextField()),
                ('payout', models.IntegerField()),
                ('result', models.CharField(choices=[('w', 'Win'), ('l', 'Lose')], max_length=1)),
                ('time', models.TimeField()),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binary', to='journal.TimeStamp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
