# Generated by Django 2.2.6 on 2019-10-17 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20191017_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='journal.Blog'),
        ),
    ]
