# Generated by Django 2.2.6 on 2019-10-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20191020_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='l_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_directory_path'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='l_text',
            field=models.TextField(default='Hello'),
        ),
        migrations.AddField(
            model_name='reason',
            name='r_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_directory_path'),
        ),
        migrations.AddField(
            model_name='reason',
            name='r_text',
            field=models.TextField(default='Hello'),
        ),
    ]
