# Generated by Django 2.2.6 on 2019-10-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20191021_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_directory_path'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_directory_path'),
        ),
    ]
